# Generated by Django 5.2.14 on 2026-05-14 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=64)),
                ('image_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['omr_image_id', 'section_type'],
            },
        ),
        migrations.CreateModel(
            name='OmrImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255, unique=True)),
                ('original_image_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
        migrations.CreateModel(
            name='FinalLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_text', models.CharField(max_length=255)),
                ('selected_model', models.CharField(max_length=64)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_label', to='validator.extractedsection')),
            ],
        ),
        migrations.AddField(
            model_name='extractedsection',
            name='omr_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='validator.omrimage'),
        ),
        migrations.CreateModel(
            name='OcrPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=64)),
                ('predicted_text', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='validator.extractedsection')),
            ],
            options={
                'ordering': ['section_id', 'model_name'],
                'unique_together': {('section', 'model_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='extractedsection',
            unique_together={('omr_image', 'section_type')},
        ),
    ]
